/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: jetty/12.0.20
 * Generated at: 2025-10-07 15:55:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.auth;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class _005fmodals_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/ADmin/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld", Long.valueOf(1664428278000L));
    _jspx_dependants.put("file:/C:/Users/ADmin/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1755841243610L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("        ");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        <!-- Modal Register -->\r\n");
      out.write("        <div class=\"modal fade authFormModal\" id=\"registerModal\" tabindex=\"-1\" aria-labelledby=\"registerModalLabel\"\r\n");
      out.write("            aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog modal-lg\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"modal-header\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"modal-body\">\r\n");
      out.write("                        <div class=\"row auth-form\">\r\n");
      out.write("                            <div class=\"col-12 col-lg-6 auth-form-left\">\r\n");
      out.write("                                <a href=\"./home.html\">\r\n");
      out.write("                                    <img class=\"auth-form-logo\"\r\n");
      out.write("                                        src=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" alt=\"Aurora\" />\r\n");
      out.write("                                    <h4 class=\"auth-form-title text-center\">\r\n");
      out.write("                                        Chào mừng bạn đến Aurora\r\n");
      out.write("                                    </h4>\r\n");
      out.write("                                    <p class=\"auth-form-desc text-center\">\r\n");
      out.write("                                        Bước vào thế giới sách – bắt đầu từ một cú click\r\n");
      out.write("                                    </p>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-12 col-lg-6 auth-form-right\">\r\n");
      out.write("                                <form class=\"auth-form-form\" id=\"form-register\">\r\n");
      out.write("                                    <div class=\"form-group mb-2\">\r\n");
      out.write("                                        <label for=\"register-fullname\" class=\"form-label\">Họ và tên</label>\r\n");
      out.write("                                        <input id=\"register-fullname\" type=\"text\" class=\"form-control\"\r\n");
      out.write("                                            placeholder=\"Nhập tên đầy đủ của bạn\" />\r\n");
      out.write("                                        <span class=\"form-message\"></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"form-group mb-2\">\r\n");
      out.write("                                        <label for=\"register-email\" class=\"form-label\">Email</label>\r\n");
      out.write("                                        <input id=\"register-email\" type=\"email\" class=\"form-control\"\r\n");
      out.write("                                            placeholder=\"Nhập email của bạn\" />\r\n");
      out.write("                                        <span class=\"form-message\"></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"form-group mb-2\">\r\n");
      out.write("                                        <label for=\"register-password\" class=\"form-label\">Mật khẩu</label>\r\n");
      out.write("                                        <div class=\"password\">\r\n");
      out.write("                                            <input id=\"register-password\" type=\"password\" class=\"form-control\"\r\n");
      out.write("                                                placeholder=\"Nhập mật khẩu của bạn\" />\r\n");
      out.write("                                            <i class=\"bi bi-eye-slash toggle-password\"></i>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <span class=\"form-message\"></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"form-group mb-2\">\r\n");
      out.write("                                        <label for=\"register-password-confirmation\" class=\"form-label\">Xác nhận mật\r\n");
      out.write("                                            khẩu</label>\r\n");
      out.write("                                        <div class=\"password\">\r\n");
      out.write("                                            <input id=\"register-password-confirmation\" type=\"password\"\r\n");
      out.write("                                                class=\"form-control\" placeholder=\"Xác nhận mật khẩu của bạn\" />\r\n");
      out.write("                                            <i class=\"bi bi-eye-slash toggle-password\"></i>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <span class=\"form-message\"></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group mb-2\">\r\n");
      out.write("                                        <label for=\"register-otp\" class=\"form-label\">Mã OTP</label>\r\n");
      out.write("                                        <label for=\"register-time\" class=\"form-label\" id=\"otp-timer\"></label>\r\n");
      out.write("                                        <div class=\"input-group\">\r\n");
      out.write("                                            <input id=\"register-otp\" type=\"number\" class=\"form-control\"\r\n");
      out.write("                                                placeholder=\"Nhập mã OTP\" />\r\n");
      out.write("                                            <button type=\"button\" class=\"button-two\" id=\"send-otp\">\r\n");
      out.write("                                                Gửi OTP\r\n");
      out.write("                                            </button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <span class=\"form-message\"></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <button class=\"button-three mt-3\">Đăng ký</button>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"text-center auth-form-have-account\">\r\n");
      out.write("                                        <span>Đã có tài khoản?\r\n");
      out.write("                                            <a href=\"#\" data-open=\"login\">\r\n");
      out.write("                                                Đăng nhập\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                        </span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- End Modal Register -->\r\n");
      out.write("\r\n");
      out.write("        <!-- Modal Login -->\r\n");
      out.write("        <div class=\"modal fade authFormModal\" id=\"loginModal\" tabindex=\"-1\" aria-labelledby=\"loginModalLabel\"\r\n");
      out.write("            aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog modal-lg\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"modal-header\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"modal-body\">\r\n");
      out.write("                        <div class=\"row auth-form\">\r\n");
      out.write("                            <div class=\"col-12 col-lg-6 auth-form-left\">\r\n");
      out.write("                                <a href=\"./home.html\">\r\n");
      out.write("                                    <img class=\"auth-form-logo\"\r\n");
      out.write("                                        src=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\" alt=\"Aurora\" />\r\n");
      out.write("                                    <h4 class=\"auth-form-title text-center\">\r\n");
      out.write("                                        Chào mừng bạn đến Aurora\r\n");
      out.write("                                    </h4>\r\n");
      out.write("                                    <p class=\"auth-form-desc text-center\">\r\n");
      out.write("                                        Bước vào thế giới sách – bắt đầu từ một cú click\r\n");
      out.write("                                    </p>\r\n");
      out.write("                                </a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-12 col-lg-6 auth-form-right\">\r\n");
      out.write("                                <form class=\"auth-form-form\" id=\"form-login\">\r\n");
      out.write("                                    <div class=\"form-group mb-2\">\r\n");
      out.write("                                        <label for=\"login-email\" class=\"form-label\">Email</label>\r\n");
      out.write("                                        <input id=\"login-email\" type=\"email\" class=\"form-control\"\r\n");
      out.write("                                            placeholder=\"Nhập email của bạn\" />\r\n");
      out.write("                                        <span class=\"form-message\"></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"form-group mb-2\">\r\n");
      out.write("                                        <label for=\"login-password\" class=\"form-label\">Mật khẩu</label>\r\n");
      out.write("                                        <div class=\"password\">\r\n");
      out.write("                                            <input id=\"login-password\" type=\"password\" class=\"form-control\"\r\n");
      out.write("                                                placeholder=\"Nhập mật khẩu của bạn\" />\r\n");
      out.write("                                            <i class=\"bi bi-eye-slash toggle-password\"></i>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <span class=\"form-message\"></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"col-6\">\r\n");
      out.write("                                            <div class=\"form-check\">\r\n");
      out.write("                                                <input tabindex=\"-1\" class=\"form-check-input\" type=\"checkbox\"\r\n");
      out.write("                                                    id=\"rememberMe\" />\r\n");
      out.write("                                                <label tabindex=\"-1\" class=\"form-check-label\" for=\"rememberMe\">\r\n");
      out.write("                                                    Ghi nhớ đăng nhập\r\n");
      out.write("                                                </label>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"col-6 text-end\">\r\n");
      out.write("                                            <a href=\"#\" tabindex=\"-1\" data-open=\"forget-password\">Quên mật khẩu?</a>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <button class=\"button-three mt-3\">Đăng nhập</button>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"text-center mb-3 divider\">\r\n");
      out.write("                                        Hoặc tiếp tục với\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"d-grid mb-3\">\r\n");
      out.write("                                        <button id=\"btn-login-google\" type=\"button\" class=\"button-two\">\r\n");
      out.write("                                            <img src=\"https://www.svgrepo.com/show/355037/google.svg\" alt=\"Google\"\r\n");
      out.write("                                                width=\"20\" class=\"me-2\" />\r\n");
      out.write("                                            Google\r\n");
      out.write("                                        </button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"text-center auth-form-have-account\">\r\n");
      out.write("                                        <span>Chưa có tài khoản?\r\n");
      out.write("                                            <a href=\"#\" data-open=\"register\">\r\n");
      out.write("                                                Đăng ký\r\n");
      out.write("                                            </a></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- End Modal Login -->\r\n");
      out.write("\r\n");
      out.write("        <!-- Modal Forget Password -->\r\n");
      out.write("        <div class=\"modal fade authFormModal\" id=\"forgetPasswordModal\" tabindex=\"-1\"\r\n");
      out.write("            aria-labelledby=\"forgetPasswordModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"modal-header\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"modal-body\">\r\n");
      out.write("                        <div class=\"row auth-form\">\r\n");
      out.write("                            <div class=\"col-12 col-lg-12 auth-form-right forget-password\">\r\n");
      out.write("                                <h4 class=\"auth-form-title text-center\">\r\n");
      out.write("                                    Quên mật khẩu\r\n");
      out.write("                                </h4>\r\n");
      out.write("                                <p class=\"auth-form-desc text-center\">\r\n");
      out.write("                                    Vui lòng nhập email để tiếp tục\r\n");
      out.write("                                </p>\r\n");
      out.write("                                <form class=\"auth-form-form\" id=\"form-forget-password\">\r\n");
      out.write("                                    <div class=\"form-group mb-2\">\r\n");
      out.write("                                        <label for=\"forget-password-email\" class=\"form-label\">Email</label>\r\n");
      out.write("                                        <input id=\"forget-password-email\" name=\"email\" type=\"email\" class=\"form-control\"\r\n");
      out.write("                                            placeholder=\"Nhập email của bạn\" />\r\n");
      out.write("                                        <span class=\"form-message\"></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <button class=\"button-three mt-3\">Tiếp tục</button>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- End Modal Forget Password -->\r\n");
      out.write("\r\n");
      out.write("        <!-- Modal Create Password -->\r\n");
      out.write("        <div class=\"modal fade authFormModal\" id=\"createPasswordModal\" tabindex=\"-1\"\r\n");
      out.write("            aria-labelledby=\"createPasswordModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("            <div class=\"modal-dialog\">\r\n");
      out.write("                <div class=\"modal-content\">\r\n");
      out.write("                    <div class=\"modal-header\">\r\n");
      out.write("                        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"modal-body\">\r\n");
      out.write("                        <div class=\"row auth-form\">\r\n");
      out.write("                            <div class=\"col-12 col-lg-12 auth-form-right forget-password\">\r\n");
      out.write("                                <h4 class=\"auth-form-title text-center\">\r\n");
      out.write("                                    Tạo mật khẩu mới\r\n");
      out.write("                                </h4>\r\n");
      out.write("                                <p class=\"auth-form-desc text-center\">\r\n");
      out.write("                                    Mã xác nhận đã gửi về email *******fc28@mail.copm\r\n");
      out.write("                                </p>\r\n");
      out.write("                                <form class=\"auth-form-form\" id=\"form-create-password\">\r\n");
      out.write("                                    <div class=\"form-group mb-2\">\r\n");
      out.write("                                        <label for=\"create-password-otp\" class=\"form-label\">Mã\r\n");
      out.write("                                            OTP</label>\r\n");
      out.write("                                        <input id=\"create-password-otp\" type=\"number\" class=\"form-control\"\r\n");
      out.write("                                            placeholder=\"Nhập mã OTP\" />\r\n");
      out.write("                                        <span class=\"form-message\"></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group mb-2\">\r\n");
      out.write("                                        <label for=\"create-password-password\" class=\"form-label\">Mật\r\n");
      out.write("                                            khẩu</label>\r\n");
      out.write("                                        <div class=\"password\">\r\n");
      out.write("                                            <input id=\"create-password-password\" type=\"password\" class=\"form-control\"\r\n");
      out.write("                                                placeholder=\"Nhập mật khẩu của bạn\" />\r\n");
      out.write("                                            <i class=\"bi bi-eye-slash toggle-password\"></i>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <span class=\"form-message\"></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"form-group mb-2\">\r\n");
      out.write("                                        <label for=\"create-password-password-confirmation\" class=\"form-label\">Xác\r\n");
      out.write("                                            nhận mật khẩu</label>\r\n");
      out.write("                                        <div class=\"password\">\r\n");
      out.write("                                            <input id=\"create-password-password-confirmation\" type=\"password\"\r\n");
      out.write("                                                class=\"form-control\" placeholder=\"Xác nhận mật khẩu của bạn\" />\r\n");
      out.write("                                            <i class=\"bi bi-eye-slash toggle-password\"></i>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <span class=\"form-message\"></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"text-center auth-form-have-account\">\r\n");
      out.write("                                        <span>Bạn chưa có OTP?\r\n");
      out.write("                                            <a href=\"#\"> Gửi lại </a></span>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <button class=\"button-three mt-3\">Xong</button>\r\n");
      out.write("                                </form>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- End Modal Create Password -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /WEB-INF/views/auth/_modals.jsp(3,8) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_c_005fset_005f0.setVar("ctx");
    // /WEB-INF/views/auth/_modals.jsp(3,8) name = value type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true deferredMethod = false expectedTypeName = java.lang.Object methodSignature = null 
    _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/auth/_modals.jsp(3,8) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager());
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /WEB-INF/views/auth/_modals.jsp(17,45) name = value type = null reqTime = true required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_c_005furl_005f0.setValue("/assets/images/branding/logo-header.png");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager());
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f1.setParent(null);
    // /WEB-INF/views/auth/_modals.jsp(106,45) name = value type = null reqTime = true required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_c_005furl_005f1.setValue("/assets/images/branding/logo-header.png");
    int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
    if (_jspx_th_c_005furl_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager());
    return false;
  }
}
