/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: jetty/12.0.20
 * Generated at: 2025-09-15 08:33:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.cart.partials;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class _005fcart_005fvoucher_005fmodal_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<div class=\"modal fade\" id=\"voucherModal\" tabindex=\"-1\" aria-hidden=\"true\">\r\n");
      out.write("    <div class=\"modal-dialog modal-dialog-scrollable\">\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("            <div class=\"modal-header\">\r\n");
      out.write("                <h5 class=\"modal-title\">Aurora Khuyến Mãi</h5>\r\n");
      out.write("                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\"></button>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"modal-body\">\r\n");
      out.write("                <div class=\"row mb-3\">\r\n");
      out.write("                    <div class=\"col-8\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" placeholder=\"Nhập mã giảm giá\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-4\">\r\n");
      out.write("                        <button class=\"btn btn-primary w-100\">Áp dụng</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <h6 class=\"fw-bold mb-2\">Mã Giảm Giá</h6>\r\n");
      out.write("                <div class=\"list-group\">\r\n");
      out.write("                    <label class=\"list-group-item d-flex justify-content-between align-items-center\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <span class=\"badge bg-primary\">Aurora</span>\r\n");
      out.write("                            <span class=\"ms-2\">Giảm 8% tối đa 30K</span><br>\r\n");
      out.write("                            <small>Cho đơn từ 199K - HSD: 25/08/25</small>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <input type=\"radio\" name=\"voucherDiscount\" value=\"discount1\"\r\n");
      out.write("                               data-text=\"Giảm 8% tối đa 30K\" data-discount=\"8\" data-type=\"percent\" data-max=\"30000\">\r\n");
      out.write("                    </label>\r\n");
      out.write("\r\n");
      out.write("                    <label class=\"list-group-item d-flex justify-content-between align-items-center\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <span class=\"badge bg-primary\">Aurora</span>\r\n");
      out.write("                            <span class=\"ms-2\">Giảm 15K</span><br>\r\n");
      out.write("                            <small>Cho đơn từ 199K - HSD: 25/08/25</small>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <input type=\"radio\" name=\"voucherDiscount\" value=\"discount2\" data-text=\"Giảm 15K\" data-discount=\"15000\">\r\n");
      out.write("                    </label>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <h6 class=\"fw-bold mt-4 mb-2\">Mã Vận Chuyển</h6>\r\n");
      out.write("                <div class=\"list-group\">\r\n");
      out.write("                    <label class=\"list-group-item d-flex justify-content-between align-items-center\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <span class=\"badge bg-success\">FREESHIP</span>\r\n");
      out.write("                            <span class=\"ms-2\">Giảm 30K</span><br>\r\n");
      out.write("                            <small>Cho đơn từ 1đ - HSD: 31/08/25</small>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <input type=\"radio\" name=\"voucherShip\" value=\"ship1\" data-text=\"Giảm 30K\" data-ship=\"30000\">\r\n");
      out.write("                    </label>\r\n");
      out.write("\r\n");
      out.write("                    <label class=\"list-group-item d-flex justify-content-between align-items-center\">\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <span class=\"badge bg-success\">FREESHIP</span>\r\n");
      out.write("                            <span class=\"ms-2\">Giảm 25K</span><br>\r\n");
      out.write("                            <small>Cho đơn từ 100K - HSD: 25/08/25</small>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <input type=\"radio\" name=\"voucherShip\" value=\"ship2\" data-text=\"Giảm 25K\" data-ship=\"25000\">\r\n");
      out.write("                    </label>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"modal-footer\">\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Trở lại</button>\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-primary\" id=\"confirmVoucher\">OK</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
