/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: jetty/12.0.20
 * Generated at: 2025-10-06 05:04:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.customer;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Users/ADmin/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/fmt-1_1.tld", Long.valueOf(1664428278000L));
    _jspx_dependants.put("jar:file:/C:/Users/ADmin/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld", Long.valueOf(1664428278000L));
    _jspx_dependants.put("file:/C:/Users/ADmin/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1755841243610L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fsetLocale_0026_005fvalue_005fnobody;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fsetLocale_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005ffmt_005fsetLocale_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_fmt_005fsetLocale_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"vi\">\r\n");
      out.write("    <head>\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/layouts/_head.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("title", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("Giỏ hàng - Aurora", request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        <link\r\n");
      out.write("            rel=\"stylesheet\"\r\n");
      out.write("            href=\"./assets/css/customer/profile/information_account.css?v=1.0.1\"\r\n");
      out.write("        />\r\n");
      out.write("    </head>\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/layouts/_header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container mt-3 information-account\">\r\n");
      out.write("            <div class=\"row \">\r\n");
      out.write("                <div class=\"col-3 col-md-2 information-account__sidebar\">\r\n");
      out.write("                    <div class=\"text-center mb-4\">\r\n");
      out.write("                        <img\r\n");
      out.write("                            src=\"./assets/images/common/avatar.png\"\r\n");
      out.write("                            alt=\"avatar\"\r\n");
      out.write("                            class=\"information-account__image\"\r\n");
      out.write("                        />\r\n");
      out.write("                        <p class=\"mt-2 fw-bold mb-0\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.fullName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    ");
      out.write("\r\n");
      out.write("                    <ul class=\"nav mb-3 \" id=\"profileTabs\" role=\"tablist\">\r\n");
      out.write("                        <li class=\"nav-item mb-2\">\r\n");
      out.write("                            <a\r\n");
      out.write("                                class=\"nav-link text-dark\"\r\n");
      out.write("                                id=\"notify-tab\"\r\n");
      out.write("                                data-bs-toggle=\"tab\"\r\n");
      out.write("                                href=\"#notify\"\r\n");
      out.write("                                role=\"tab\"\r\n");
      out.write("                            >\r\n");
      out.write("                                <i class=\"bi bi-bell me-2\"></i> Thông báo\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item mb-2\">\r\n");
      out.write("                            <a\r\n");
      out.write("                                class=\"nav-link text-dark active\"\r\n");
      out.write("                                href=\"/profile\"\r\n");
      out.write("                            >\r\n");
      out.write("                                <i class=\"bi bi-person me-2\"></i> Hồ sơ\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item mb-2\">\r\n");
      out.write("                            <a class=\"nav-link text-dark \" href=\"/address\">\r\n");
      out.write("                                <i class=\"bi bi-geo-alt me-2\"></i> Địa Chỉ\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item mb-2\">\r\n");
      out.write("                            <a class=\"nav-link text-dark\" href=\"/order\">\r\n");
      out.write("                                <i class=\"bi bi-box-seam me-2\"></i> Quản lý đơn\r\n");
      out.write("                                hàng\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-9 col-md-10 \">\r\n");
      out.write("                    <div class=\"tab-content\" id=\"profileTabsContent\">\r\n");
      out.write("                        ");
      out.write("\r\n");
      out.write("                        <div\r\n");
      out.write("                            class=\"tab-pane fade\"\r\n");
      out.write("                            id=\"notify\"\r\n");
      out.write("                            role=\"tabpanel\"\r\n");
      out.write("                            aria-labelledby=\"notify-tab\"\r\n");
      out.write("                        >\r\n");
      out.write("                            <div class=\"text-center mt-5\">\r\n");
      out.write("                                <img\r\n");
      out.write("                                    src=\"./assets/images/mascot_fail.svg\"\r\n");
      out.write("                                    alt=\"\"\r\n");
      out.write("                                />\r\n");
      out.write("                                <p class=\"text-muted mt-3\">Chưa có thông báo</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        ");
      out.write("\r\n");
      out.write("                        <div\r\n");
      out.write("                            class=\"tab-pane fade show active\"\r\n");
      out.write("                            id=\"profile\"\r\n");
      out.write("                            role=\"tabpanel\"\r\n");
      out.write("                            aria-labelledby=\"profile-tab\"\r\n");
      out.write("                        >\r\n");
      out.write("                            <div class=\"profile\">\r\n");
      out.write("                                <div class=\"d-flex justify-content-between\">\r\n");
      out.write("                                    <h5 class=\"mb-3 profile-title\">\r\n");
      out.write("                                        Hồ Sơ Của Tôi\r\n");
      out.write("                                    </h5>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <p class=\"profile-des\">\r\n");
      out.write("                                    Quản lý thông tin hồ sơ để bảo mật tài khoản\r\n");
      out.write("                                </p>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                    <div class=\"col-md-8\">\r\n");
      out.write("                                        <form>\r\n");
      out.write("                                            <div\r\n");
      out.write("                                                class=\"mb-3 row align-items-center\"\r\n");
      out.write("                                            >\r\n");
      out.write("                                                <label\r\n");
      out.write("                                                    class=\"col-sm-3 col-form-label\"\r\n");
      out.write("                                                    >Tên:</label\r\n");
      out.write("                                                >\r\n");
      out.write("                                                <div class=\"col-sm-9\">\r\n");
      out.write("                                                    <input\r\n");
      out.write("                                                        type=\"text\"\r\n");
      out.write("                                                        class=\"form-control\"\r\n");
      out.write("                                                        value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.fullName}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("                                                    />\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("\r\n");
      out.write("                                            <div\r\n");
      out.write("                                                class=\"mb-3 row align-items-center\"\r\n");
      out.write("                                            >\r\n");
      out.write("                                                <label\r\n");
      out.write("                                                    class=\"col-sm-3 col-form-label\"\r\n");
      out.write("                                                    >Email:</label\r\n");
      out.write("                                                >\r\n");
      out.write("                                                <div\r\n");
      out.write("                                                    class=\"col-sm-9 d-flex align-items-center\"\r\n");
      out.write("                                                >\r\n");
      out.write("                                                    <span\r\n");
      out.write("                                                        class=\"me-2 text-truncate\"\r\n");
      out.write("                                                        >");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.email}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span\r\n");
      out.write("                                                    >\r\n");
      out.write("                                                    <a\r\n");
      out.write("                                                        href=\"#\"\r\n");
      out.write("                                                        class=\"btn btn-link btn-sm p-0\"\r\n");
      out.write("                                                        >Thay Đổi</a\r\n");
      out.write("                                                    >\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("\r\n");
      out.write("                                            <div\r\n");
      out.write("                                                class=\"mb-3 row align-items-center\"\r\n");
      out.write("                                            >\r\n");
      out.write("                                                <label\r\n");
      out.write("                                                    class=\"col-sm-3 col-form-label\"\r\n");
      out.write("                                                    >Số điện thoại:</label\r\n");
      out.write("                                                >\r\n");
      out.write("                                                <div\r\n");
      out.write("                                                    class=\"col-sm-9 d-flex align-items-center\"\r\n");
      out.write("                                                >\r\n");
      out.write("                                                    <span\r\n");
      out.write("                                                        class=\"me-2 text-truncate\"\r\n");
      out.write("                                                        >");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.phone}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span\r\n");
      out.write("                                                    >\r\n");
      out.write("                                                    <a\r\n");
      out.write("                                                        href=\"#\"\r\n");
      out.write("                                                        class=\"btn btn-link btn-sm p-0\"\r\n");
      out.write("                                                        >Thay Đổi</a\r\n");
      out.write("                                                    >\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("\r\n");
      out.write("                                            <div class=\"row\">\r\n");
      out.write("                                                <div class=\"col-sm-9\">\r\n");
      out.write("                                                    <button\r\n");
      out.write("                                                        type=\"submit\"\r\n");
      out.write("                                                        class=\"button-four\"\r\n");
      out.write("                                                    >\r\n");
      out.write("                                                        Lưu\r\n");
      out.write("                                                    </button>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </form>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div\r\n");
      out.write("                                        class=\"col-md-4 text-center profile-update__img\"\r\n");
      out.write("                                    >\r\n");
      out.write("                                        <div class=\"mb-3\">\r\n");
      out.write("                                            <img\r\n");
      out.write("                                                src=\"./assets/images/common/avatar.png\"\r\n");
      out.write("                                                class=\"profile-img\"\r\n");
      out.write("                                                alt=\"Avatar\"\r\n");
      out.write("                                            />\r\n");
      out.write("                                            <div class=\"mt-3\">\r\n");
      out.write("                                                <input\r\n");
      out.write("                                                    type=\"file\"\r\n");
      out.write("                                                    class=\"d-none\"\r\n");
      out.write("                                                    id=\"avatarInput\"\r\n");
      out.write("                                                />\r\n");
      out.write("                                                <label\r\n");
      out.write("                                                    for=\"avatarInput\"\r\n");
      out.write("                                                    class=\"button-five\"\r\n");
      out.write("                                                    >Chọn Ảnh</label\r\n");
      out.write("                                                >\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/layouts/_footer.jsp", out, false);
      out.write("\r\n");
      out.write("        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/layouts/_scripts.jsp", out, false);
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /WEB-INF/views/customer/profile.jsp(3,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_c_005fset_005f0.setVar("ctx");
    // /WEB-INF/views/customer/profile.jsp(3,0) name = value type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true deferredMethod = false expectedTypeName = java.lang.Object methodSignature = null 
    _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/customer/profile.jsp(3,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager());
    return false;
  }

  private boolean _jspx_meth_fmt_005fsetLocale_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  fmt:setLocale
    org.apache.taglibs.standard.tag.rt.fmt.SetLocaleTag _jspx_th_fmt_005fsetLocale_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.SetLocaleTag) _005fjspx_005ftagPool_005ffmt_005fsetLocale_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.SetLocaleTag.class);
    _jspx_th_fmt_005fsetLocale_005f0.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fsetLocale_005f0.setParent(null);
    // /WEB-INF/views/customer/profile.jsp(5,0) name = value type = null reqTime = true required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_fmt_005fsetLocale_005f0.setValue("vi_VN");
    int _jspx_eval_fmt_005fsetLocale_005f0 = _jspx_th_fmt_005fsetLocale_005f0.doStartTag();
    if (_jspx_th_fmt_005fsetLocale_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fsetLocale_0026_005fvalue_005fnobody.reuse(_jspx_th_fmt_005fsetLocale_005f0);
    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fsetLocale_005f0, _jsp_getInstanceManager());
    return false;
  }
}
