/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: jetty/12.0.20
 * Generated at: 2025-10-03 18:47:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.shop;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class orderManage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("file:/C:/Users/ASUS/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1754287995726L));
    _jspx_dependants.put("jar:file:/C:/Users/ASUS/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/fmt.tld", Long.valueOf(1664428278000L));
    _jspx_dependants.put("jar:file:/C:/Users/ASUS/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c.tld", Long.valueOf(1664428278000L));
    _jspx_dependants.put("jar:file:/C:/Users/ASUS/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/fn.tld", Long.valueOf(1664428278000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("        \r\n");
      out.write("            \r\n");
      out.write("                ");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                ");
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                <!DOCTYPE html>\r\n");
      out.write("                <html lang=\"vi\">\r\n");
      out.write("\r\n");
      out.write("                <head>\r\n");
      out.write("                    <meta charset=\"UTF-8\">\r\n");
      out.write("                    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("                    <title>Quản lý Đơn hàng - Aurora Bookstore</title>\r\n");
      out.write("                    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("                        rel=\"stylesheet\">\r\n");
      out.write("                    <link rel=\"stylesheet\"\r\n");
      out.write("                        href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css\">\r\n");
      out.write("                    <link rel=\"stylesheet\"\r\n");
      out.write("                        href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css\">\r\n");
      out.write("                    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/common/globals.css\">\r\n");
      out.write("                    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/catalog/home.css\" />\r\n");
      out.write("                    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/admin/adminPage.css\" />\r\n");
      out.write("                    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/css/shop/orderManagement.css\">\r\n");
      out.write("                </head>\r\n");
      out.write("\r\n");
      out.write("                <body class=\"sb-nav-fixed\">\r\n");
      out.write("                    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/layouts/_header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <div id=\"layoutSidenav\">\r\n");
      out.write("                        ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/layouts/_sidebarShop.jsp", out, false);
      out.write("\r\n");
      out.write("                        <div id=\"layoutSidenav_content\">\r\n");
      out.write("                            <main>\r\n");
      out.write("                                <div class=\"container-fluid px-4\">\r\n");
      out.write("                                    <!-- Page Header -->\r\n");
      out.write("                                    <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("                                        <h1 class=\"mt-4 order-management-title\">Tất cả</h1>\r\n");
      out.write("                                        <nav aria-label=\"breadcrumb\">\r\n");
      out.write("                                            <ol class=\"breadcrumb\">\r\n");
      out.write("                                                <li class=\"breadcrumb-item\"><a href=\"home.html\">Trang chủ</a></li>\r\n");
      out.write("                                                <li class=\"breadcrumb-item\"><a href=\"adminDashboard.html\">Dashboard</a>\r\n");
      out.write("                                                </li>\r\n");
      out.write("                                                <li class=\"breadcrumb-item active\" aria-current=\"page\">Đơn hàng</li>\r\n");
      out.write("                                            </ol>\r\n");
      out.write("                                        </nav>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <!-- Order Status Tabs -->\r\n");
      out.write("                                    <div class=\"row mt-4\">\r\n");
      out.write("                                        <div class=\"col-12\">\r\n");
      out.write("                                            <div class=\"card\">\r\n");
      out.write("                                                <div class=\"card-body\">\r\n");
      out.write("                                                    <ul class=\"nav nav-tabs order-tabs\" id=\"orderTabs\" role=\"tablist\">\r\n");
      out.write("                                                        <li class=\"nav-item\" role=\"presentation\">\r\n");
      out.write("                                                            <button class=\"nav-link active\" id=\"all-tab\"\r\n");
      out.write("                                                                data-bs-toggle=\"tab\" data-bs-target=\"#all\" type=\"button\"\r\n");
      out.write("                                                                role=\"tab\">\r\n");
      out.write("                                                                Tất cả\r\n");
      out.write("                                                            </button>\r\n");
      out.write("                                                        </li>\r\n");
      out.write("                                                        <li class=\"nav-item\" role=\"presentation\">\r\n");
      out.write("                                                            <button class=\"nav-link\" id=\"pending-tab\"\r\n");
      out.write("                                                                data-bs-toggle=\"tab\" data-bs-target=\"#pending\"\r\n");
      out.write("                                                                type=\"button\" role=\"tab\">\r\n");
      out.write("                                                                Chờ xác nhận\r\n");
      out.write("                                                            </button>\r\n");
      out.write("                                                        </li>\r\n");
      out.write("                                                        <li class=\"nav-item\" role=\"presentation\">\r\n");
      out.write("                                                            <button class=\"nav-link\" id=\"confirmed-tab\"\r\n");
      out.write("                                                                data-bs-toggle=\"tab\" data-bs-target=\"#confirmed\"\r\n");
      out.write("                                                                type=\"button\" role=\"tab\">\r\n");
      out.write("                                                                Chờ lấy hàng\r\n");
      out.write("                                                            </button>\r\n");
      out.write("                                                        </li>\r\n");
      out.write("                                                        <li class=\"nav-item\" role=\"presentation\">\r\n");
      out.write("                                                            <button class=\"nav-link\" id=\"shipping-tab\"\r\n");
      out.write("                                                                data-bs-toggle=\"tab\" data-bs-target=\"#shipping\"\r\n");
      out.write("                                                                type=\"button\" role=\"tab\">\r\n");
      out.write("                                                                Đang giao (18)\r\n");
      out.write("                                                            </button>\r\n");
      out.write("                                                        </li>\r\n");
      out.write("                                                        <li class=\"nav-item\" role=\"presentation\">\r\n");
      out.write("                                                            <button class=\"nav-link\" id=\"delivered-tab\"\r\n");
      out.write("                                                                data-bs-toggle=\"tab\" data-bs-target=\"#delivered\"\r\n");
      out.write("                                                                type=\"button\" role=\"tab\">\r\n");
      out.write("                                                                Đã giao\r\n");
      out.write("                                                            </button>\r\n");
      out.write("                                                        </li>\r\n");
      out.write("                                                        <li class=\"nav-item\" role=\"presentation\">\r\n");
      out.write("                                                            <button class=\"nav-link\" id=\"cancelled-tab\"\r\n");
      out.write("                                                                data-bs-toggle=\"tab\" data-bs-target=\"#cancelled\"\r\n");
      out.write("                                                                type=\"button\" role=\"tab\">\r\n");
      out.write("                                                                Trả hàng/Hoàn tiền/Hủy (4)\r\n");
      out.write("                                                            </button>\r\n");
      out.write("                                                        </li>\r\n");
      out.write("                                                    </ul>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <!-- Warning Alert -->\r\n");
      out.write("                                    <div class=\"row mt-3\">\r\n");
      out.write("                                        <div class=\"col-12\">\r\n");
      out.write("                                            <div class=\"alert alert-warning alert-dismissible fade show\" role=\"alert\">\r\n");
      out.write("                                                <i class=\"bi bi-exclamation-triangle me-2\"></i>\r\n");
      out.write("                                                <strong>Lưu ý:</strong> Tỷ lệ đơn hàng không thành công của Shop trong\r\n");
      out.write("                                                tuần trước là 10%. Nếu tỷ lệ này vượt quá 10% vào tuần này, bạn có thể\r\n");
      out.write("                                                bị phạt tối đa 2 điểm tín. Vui lòng cập nhật giao hàng đúng hạn để tránh\r\n");
      out.write("                                                bị phạt.\r\n");
      out.write("                                                <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\"\r\n");
      out.write("                                                    aria-label=\"Close\"></button>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <!-- Search and Filter Section -->\r\n");
      out.write("                                    <div class=\"row mt-3\">\r\n");
      out.write("                                        <div class=\"col-12\">\r\n");
      out.write("                                            <div class=\"card\">\r\n");
      out.write("                                                <div class=\"card-body\">\r\n");
      out.write("                                                    <div class=\"row g-3\">\r\n");
      out.write("                                                        <div class=\"col-md-3\">\r\n");
      out.write("                                                            <label for=\"orderSearch\" class=\"form-label\">Mã đơn\r\n");
      out.write("                                                                hàng</label>\r\n");
      out.write("                                                            <input type=\"text\" class=\"form-control\" id=\"orderSearch\"\r\n");
      out.write("                                                                placeholder=\"Nhập mã đơn hàng\">\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"col-md-3\">\r\n");
      out.write("                                                            <label for=\"customerSearch\" class=\"form-label\">Tên khách\r\n");
      out.write("                                                                hàng</label>\r\n");
      out.write("                                                            <input type=\"text\" class=\"form-control\" id=\"customerSearch\"\r\n");
      out.write("                                                                placeholder=\"Nhập tên khách hàng\">\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"col-md-2\">\r\n");
      out.write("                                                            <label for=\"orderStatus\" class=\"form-label\">Đơn vị vận\r\n");
      out.write("                                                                chuyển</label>\r\n");
      out.write("                                                            <select class=\"form-select\" id=\"orderStatus\">\r\n");
      out.write("                                                                <option value=\"\">Tất cả ĐVVC</option>\r\n");
      out.write("                                                                <option value=\"ghn\">Giao hàng nhanh</option>\r\n");
      out.write("                                                                <option value=\"ghtk\">Giao hàng tiết kiệm</option>\r\n");
      out.write("                                                                <option value=\"viettel\">Viettel Post</option>\r\n");
      out.write("                                                            </select>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"col-md-2\">\r\n");
      out.write("                                                            <label class=\"form-label\">&nbsp;</label>\r\n");
      out.write("                                                            <div class=\"d-flex gap-2\">\r\n");
      out.write("                                                                <button type=\"button\" class=\"btn btn-primary\">Áp\r\n");
      out.write("                                                                    dụng</button>\r\n");
      out.write("                                                                <button type=\"button\"\r\n");
      out.write("                                                                    class=\"btn btn-outline-secondary\">Đặt lại</button>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <!-- Orders Summary -->\r\n");
      out.write("                                    <div class=\"row mt-3\">\r\n");
      out.write("                                        <div class=\"col-12\">\r\n");
      out.write("                                            <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("                                                <h5 class=\"mb-0\">2373 Đơn hàng</h5>\r\n");
      out.write("                                                <div class=\"d-flex align-items-center gap-3\">\r\n");
      out.write("                                                    <span class=\"text-muted\">Sản phẩm</span>\r\n");
      out.write("                                                    <span class=\"text-muted\">Tổng Đơn hàng</span>\r\n");
      out.write("                                                    <span class=\"text-muted\">Trạng thái</span>\r\n");
      out.write("                                                    <span class=\"text-muted\">Đơn vị vận chuyển</span>\r\n");
      out.write("                                                    <span class=\"text-muted\">Đơn vị vận chuyển</span>\r\n");
      out.write("                                                    <span class=\"text-muted\">Thao tác</span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <!-- Tab Content -->\r\n");
      out.write("                                    <div class=\"tab-content mt-3\" id=\"orderTabContent\">\r\n");
      out.write("                                        <div class=\"tab-pane fade show active\" id=\"all\" role=\"tabpanel\">\r\n");
      out.write("                                            <!-- Order Items -->\r\n");
      out.write("                                            <div class=\"order-list\">\r\n");
      out.write("                                                <!-- Order 1 -->\r\n");
      out.write("                                                <div class=\"order-item\">\r\n");
      out.write("                                                    <div class=\"order-header\">\r\n");
      out.write("                                                        <div class=\"d-flex align-items-center\">\r\n");
      out.write("                                                            <span class=\"order-id\">Gemini2019</span>\r\n");
      out.write("                                                            <span class=\"badge bg-danger ms-2\">\r\n");
      out.write("                                                                <i class=\"bi bi-flag\"></i>\r\n");
      out.write("                                                            </span>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"order-code\">Mã đơn hàng: 250912440CPRXU</div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"order-content\">\r\n");
      out.write("                                                        <div class=\"row align-items-center\">\r\n");
      out.write("                                                            <div class=\"col-md-4\">\r\n");
      out.write("                                                                <div class=\"d-flex\">\r\n");
      out.write("                                                                    <img src=\"./assets/images/book-placeholder.jpg\"\r\n");
      out.write("                                                                        alt=\"Book\" class=\"order-product-image\">\r\n");
      out.write("                                                                    <div class=\"ms-3\">\r\n");
      out.write("                                                                        <h6 class=\"product-name\">Cây Thúc Thần Kỳ, Cây\r\n");
      out.write("                                                                            Cầm Đồng Trong Tín Điều, và Thú Handmade:\r\n");
      out.write("                                                                            Nghệ Thuật Thủ Công Việt Tân Hành</h6>\r\n");
      out.write("                                                                        <p class=\"text-muted mb-0\">x1</p>\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                            <div class=\"col-md-2\">\r\n");
      out.write("                                                                <div class=\"order-total\">\r\n");
      out.write("                                                                    <div class=\"fw-bold\">643.400</div>\r\n");
      out.write("                                                                    <div class=\"text-muted small\">Tổng tiền khi chưa\r\n");
      out.write("                                                                        khấu trừ</div>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                            <div class=\"col-md-2\">\r\n");
      out.write("                                                                <div class=\"order-status\">\r\n");
      out.write("                                                                    <span class=\"badge bg-warning\">Đã giao cho\r\n");
      out.write("                                                                        ĐVVC</span>\r\n");
      out.write("                                                                    <div class=\"text-muted small\">Giao hàng đang giao\r\n");
      out.write("                                                                        cho Người mua</div>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                            <div class=\"col-md-2\">\r\n");
      out.write("                                                                <div class=\"shipping-info\">\r\n");
      out.write("                                                                    <div class=\"fw-bold\">Nhanh</div>\r\n");
      out.write("                                                                    <div class=\"text-muted small\">SPX Express</div>\r\n");
      out.write("                                                                    <div class=\"text-muted small\">SP1A3B2C3D4E5F6</div>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                            <div class=\"col-md-2\">\r\n");
      out.write("                                                                <div class=\"order-actions\" data-productid=\"1\">\r\n");
      out.write("                                                                    <a href=\"\" class=\"btn btn-outline-primary btn-sm\">\r\n");
      out.write("                                                                        Xem chi tiết\r\n");
      out.write("                                                                    </a>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                <!-- Order 2 -->\r\n");
      out.write("                                                <div class=\"order-item\">\r\n");
      out.write("                                                    <div class=\"order-header\">\r\n");
      out.write("                                                        <div class=\"d-flex align-items-center\">\r\n");
      out.write("                                                            <span class=\"order-id\">anhhieuvan6453</span>\r\n");
      out.write("                                                            <span class=\"badge bg-danger ms-2\">\r\n");
      out.write("                                                                <i class=\"bi bi-flag\"></i>\r\n");
      out.write("                                                            </span>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"order-code\">Mã đơn hàng: 250918C3F8P6</div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"order-content\">\r\n");
      out.write("                                                        <div class=\"row align-items-center\">\r\n");
      out.write("                                                            <div class=\"col-md-4\">\r\n");
      out.write("                                                                <div class=\"d-flex\">\r\n");
      out.write("                                                                    <img src=\"./assets/images/book-placeholder.jpg\"\r\n");
      out.write("                                                                        alt=\"Book\" class=\"order-product-image\">\r\n");
      out.write("                                                                    <div class=\"ms-3\">\r\n");
      out.write("                                                                        <h6 class=\"product-name\">PHÁP HOA TÔN GIÁO Những\r\n");
      out.write("                                                                            Lưu Ý Lớp Mẫn Sáu Hạt và Bài Tập Handmade,\r\n");
      out.write("                                                                            Tr</h6>\r\n");
      out.write("                                                                        <p class=\"text-muted mb-0\">x1</p>\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                            <div class=\"col-md-2\">\r\n");
      out.write("                                                                <div class=\"order-total\">\r\n");
      out.write("                                                                    <div class=\"fw-bold\">412.100</div>\r\n");
      out.write("                                                                    <div class=\"text-muted small\">Thành tiền khi chưa\r\n");
      out.write("                                                                        khấu trừ</div>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                            <div class=\"col-md-2\">\r\n");
      out.write("                                                                <div class=\"order-status\">\r\n");
      out.write("                                                                    <span class=\"badge bg-warning\">Đã giao cho\r\n");
      out.write("                                                                        ĐVVC</span>\r\n");
      out.write("                                                                    <div class=\"text-muted small\">Giao hàng đang giao\r\n");
      out.write("                                                                        cho Người mua</div>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                            <div class=\"col-md-2\">\r\n");
      out.write("                                                                <div class=\"shipping-info\">\r\n");
      out.write("                                                                    <div class=\"fw-bold\">Nhanh</div>\r\n");
      out.write("                                                                    <div class=\"text-muted small\">SPX Express</div>\r\n");
      out.write("                                                                    <div class=\"text-muted small\">SP1A3B2C3D4E5F6</div>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                            <div class=\"col-md-2\">\r\n");
      out.write("                                                                <div class=\"order-actions\">\r\n");
      out.write("                                                                    <a href=\"/order?productId=1\"\r\n");
      out.write("                                                                        class=\"btn btn-outline-primary btn-sm\">\r\n");
      out.write("                                                                        Xem chi tiết\r\n");
      out.write("                                                                    </a>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                <!-- Order 3 -->\r\n");
      out.write("                                                <div class=\"order-item\">\r\n");
      out.write("                                                    <div class=\"order-header\">\r\n");
      out.write("                                                        <div class=\"d-flex align-items-center\">\r\n");
      out.write("                                                            <span class=\"order-id\">lonha1417</span>\r\n");
      out.write("                                                            <span class=\"badge bg-danger ms-2\">\r\n");
      out.write("                                                                <i class=\"bi bi-flag\"></i>\r\n");
      out.write("                                                            </span>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                        <div class=\"order-code\">Mã đơn hàng: 250914GF1H4G03</div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                    <div class=\"order-content\">\r\n");
      out.write("                                                        <div class=\"row align-items-center\">\r\n");
      out.write("                                                            <div class=\"col-md-4\">\r\n");
      out.write("                                                                <div class=\"d-flex\">\r\n");
      out.write("                                                                    <img src=\"./assets/images/book-placeholder.jpg\"\r\n");
      out.write("                                                                        alt=\"Book\" class=\"order-product-image\">\r\n");
      out.write("                                                                    <div class=\"ms-3\">\r\n");
      out.write("                                                                        <h6 class=\"product-name\">1 Lúp Đào Kiểm Những\r\n");
      out.write("                                                                            Suy Nghĩ Để Thương - Lúp Ở Át Tương Tự -\r\n");
      out.write("                                                                            Dành - Tương Tự Những Suy Nghĩ Để Thương\r\n");
      out.write("                                                                        </h6>\r\n");
      out.write("                                                                        <p class=\"text-muted mb-0\">x1</p>\r\n");
      out.write("                                                                    </div>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                            <div class=\"col-md-2\">\r\n");
      out.write("                                                                <div class=\"order-total\">\r\n");
      out.write("                                                                    <div class=\"fw-bold\">1166.625</div>\r\n");
      out.write("                                                                    <div class=\"text-muted small\">Thành tiền khi chưa\r\n");
      out.write("                                                                        khấu trừ</div>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                            <div class=\"col-md-2\">\r\n");
      out.write("                                                                <div class=\"order-status\">\r\n");
      out.write("                                                                    <span class=\"badge bg-warning\">Đã giao cho\r\n");
      out.write("                                                                        ĐVVC</span>\r\n");
      out.write("                                                                    <div class=\"text-muted small\">Giao hàng đang giao\r\n");
      out.write("                                                                        cho Người mua</div>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                            <div class=\"col-md-2\">\r\n");
      out.write("                                                                <div class=\"shipping-info\">\r\n");
      out.write("                                                                    <div class=\"fw-bold\">Nhanh</div>\r\n");
      out.write("                                                                    <div class=\"text-muted small\">SPX Express</div>\r\n");
      out.write("                                                                    <div class=\"text-muted small\">SP1A3B2C3D4E5F6</div>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                            <div class=\"col-md-2\">\r\n");
      out.write("                                                                <div class=\"order-actions\" data-productid=\"1\">\r\n");
      out.write("                                                                    <a href=\"/order?productId=1\"\r\n");
      out.write("                                                                        class=\"btn btn-outline-primary btn-sm\">\r\n");
      out.write("                                                                        Xem chi tiết\r\n");
      out.write("                                                                    </a>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                        <!-- Pagination -->\r\n");
      out.write("                                        <div class=\"row mt-4\">\r\n");
      out.write("                                            <div class=\"col-12\">\r\n");
      out.write("                                                <div class=\"pagination-container\">\r\n");
      out.write("                                                    <nav aria-label=\"Order pagination\">\r\n");
      out.write("                                                        <ul class=\"pagination\">\r\n");
      out.write("                                                            <li class=\"page-item disabled\">\r\n");
      out.write("                                                                <a class=\"page-link\" href=\"#\" tabindex=\"-1\"\r\n");
      out.write("                                                                    aria-disabled=\"true\">Trước</a>\r\n");
      out.write("                                                            </li>\r\n");
      out.write("                                                            <li class=\"page-item active\" aria-current=\"page\">\r\n");
      out.write("                                                                <a class=\"page-link\" href=\"#\">1</a>\r\n");
      out.write("                                                            </li>\r\n");
      out.write("                                                            <li class=\"page-item\">\r\n");
      out.write("                                                                <a class=\"page-link\" href=\"#\">2</a>\r\n");
      out.write("                                                            </li>\r\n");
      out.write("                                                            <li class=\"page-item\">\r\n");
      out.write("                                                                <a class=\"page-link\" href=\"#\">3</a>\r\n");
      out.write("                                                            </li>\r\n");
      out.write("                                                            <li class=\"page-item\">\r\n");
      out.write("                                                                <span class=\"page-link\">...</span>\r\n");
      out.write("                                                            </li>\r\n");
      out.write("                                                            <li class=\"page-item\">\r\n");
      out.write("                                                                <a class=\"page-link\" href=\"#\">95</a>\r\n");
      out.write("                                                            </li>\r\n");
      out.write("                                                            <li class=\"page-item\">\r\n");
      out.write("                                                                <a class=\"page-link\" href=\"#\">Sau</a>\r\n");
      out.write("                                                            </li>\r\n");
      out.write("                                                        </ul>\r\n");
      out.write("                                                    </nav>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </main>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/layouts/_footer.jsp?v=1.0.1", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("                    <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ctx}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/assets/js/shop/orderManagement.js?v=1.0.1\"></script>\r\n");
      out.write("                </body>\r\n");
      out.write("\r\n");
      out.write("                </html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /WEB-INF/views/shop/orderManage.jsp(5,16) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_c_005fset_005f0.setVar("pageTitle");
    // /WEB-INF/views/shop/orderManage.jsp(5,16) name = value type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true deferredMethod = false expectedTypeName = java.lang.Object methodSignature = null 
    _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/shop/orderManage.jsp(5,16) 'Aurora'",_jsp_getExpressionFactory().createValueExpression("Aurora",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager());
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f1.setParent(null);
    // /WEB-INF/views/shop/orderManage.jsp(6,16) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_c_005fset_005f1.setVar("ctx");
    // /WEB-INF/views/shop/orderManage.jsp(6,16) name = value type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true deferredMethod = false expectedTypeName = java.lang.Object methodSignature = null 
    _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/shop/orderManage.jsp(6,16) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
    if (_jspx_th_c_005fset_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
    org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager());
    return false;
  }
}
